/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocationDto } from './location-dto.interface';


export interface AddressDto { 
    /**
     * Street
     */
    street?: string;
    /**
     * City
     */
    city?: string;
    /**
     * State
     */
    state?: string;
    /**
     * Zip code
     */
    postalCode?: string;
    /**
     * Country
     */
    country?: string;
    /**
     * Is default address
     */
    isDefaultAddress?: boolean;
    /**
     * Location
     */
    location?: LocationDto;
}

