/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AudienceFilterDto { 
    /**
     * Field name to filter on, e.g. \"country\", \"age\", \"tags\"
     */
    field: string;
    /**
     * Supported operators: eq, in, contains
     */
    operator: string;
    /**
     * Value can be string, number, boolean or array depending on operator
     */
    value: object;
}

