/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CaptureLeadCommand { 
    firstName?: string;
    lastName?: string;
    email?: string;
    mobileNumber?: string;
    source: string;
    formData?: object;
    apiKey?: string;
}

