/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoutingRuleResponse } from './routing-rule-response.interface';


export interface CaptureConfigDto { 
    id: string;
    name: string;
    platform: object;
    apiKey: string;
    isActive: boolean;
    allowedDomains: Array<string>;
    fieldMapping?: object;
    routingRule?: RoutingRuleResponse;
    createdAt: string;
}

