/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDto } from './address-dto.interface';


export interface CreateContactCommand { 
    /**
     * Email
     */
    email: string;
    /**
     * firstName
     */
    firstName: string;
    /**
     * LastName
     */
    lastName: string;
    /**
     * Mobile number
     */
    mobileNumber: string;
    /**
     * Date of birth
     */
    dateOfBirth?: string;
    /**
     * Job title
     */
    jobTitle?: string;
    /**
     * Source of the contact
     */
    source?: CreateContactCommandSourceEnum;
    /**
     * Gender
     */
    gender?: CreateContactCommandGenderEnum;
    /**
     * Company name
     */
    companyName?: string;
    /**
     * Landline phone number
     */
    phone?: string;
    /**
     * Address
     */
    address?: AddressDto;
    /**
     * Tags for categorization
     */
    tags?: Array<string>;
}
export enum CreateContactCommandSourceEnum {
    Website = 'Website',
    Referral = 'Referral',
    SocialMedia = 'Social Media',
    Event = 'Event',
    ColdCall = 'Cold Call',
    Email = 'Email',
    BackOffice = 'Back Office',
    LinkedIn = 'LinkedIn',
    Facebook = 'Facebook',
    Twitter = 'Twitter',
    Google = 'Google',
    Instagram = 'Instagram',
    YouTube = 'YouTube',
    Pinterest = 'Pinterest',
    Snapchat = 'Snapchat',
    TikTok = 'TikTok',
    Reddit = 'Reddit',
    Quora = 'Quora',
    Yelp = 'Yelp',
    Campaign = 'Campaign',
    Other = 'Other'
};
export enum CreateContactCommandGenderEnum {
    Male = 'Male',
    Female = 'Female'
};



