/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateTaskCommand { 
    /**
     * The user whom the task is assigned
     */
    ownerId: string;
    /**
     * Entry related to entity, contactId
     */
    relatedToId: string;
    /**
     * Depending entry type
     */
    relatedToType: string;
    taskType: CreateTaskCommandTaskTypeEnum;
    /**
     * Task title
     */
    title: string;
    /**
     * Task description
     */
    description: string;
    /**
     * Due Date
     */
    dueDate: string;
    /**
     * Due Date
     */
    dueDatetime: string;
    /**
     * Mark task as completed
     */
    markedAsCompleted: boolean;
    /**
     * Associate collaborator
     */
    collaboratorIds: Array<string>;
}
export enum CreateTaskCommandTaskTypeEnum {
    FollowUp = 'follow up',
    CallReminder = 'call reminder'
};



