/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AudienceFilterDto } from './audience-filter-dto.interface';


export interface CreateCampaignCommand { 
    /**
     * Name of the campaign
     */
    name: string;
    /**
     * Channel to send the campaign, e.g. Email, SMS, Push
     */
    channel: CreateCampaignCommandChannelEnum;
    /**
     * Optional message template ID to use for this campaign
     */
    templateId?: string;
    /**
     * Optional subject for the campaign (used for email)
     */
    subject?: string;
    /**
     * Optional body for the campaign
     */
    body?: string;
    /**
     * Optional filters for the campaign audience
     */
    audienceFilters?: Array<AudienceFilterDto>;
    /**
     * Optional date and time to schedule the campaign
     */
    scheduledAt?: string;
}
export enum CreateCampaignCommandChannelEnum {
    Email = 'email',
    Sms = 'sms',
    Whatsapp = 'whatsapp'
};



