/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateTerritoryCommand { 
    /**
     * Name of the territory
     */
    name: string;
    description: string;
    /**
     * Territory children
     */
    childrenIds?: Array<string>;
    parentId?: string;
}

