/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateLeadCommand { 
    email: string;
    firstName: string;
    lastName: string;
    mobileNumber: string;
    source: CreateLeadCommandSourceEnum;
    productInterest?: string;
    estimatedValue?: number;
    priority?: CreateLeadCommandPriorityEnum;
    notes?: string;
    tags?: Array<string>;
}
export enum CreateLeadCommandSourceEnum {
    Website = 'Website',
    Referral = 'Referral',
    SocialMedia = 'Social Media',
    Event = 'Event',
    ColdCall = 'Cold Call',
    Email = 'Email',
    BackOffice = 'Back Office',
    LinkedIn = 'LinkedIn',
    Facebook = 'Facebook',
    Twitter = 'Twitter',
    Google = 'Google',
    Instagram = 'Instagram',
    YouTube = 'YouTube',
    Pinterest = 'Pinterest',
    Snapchat = 'Snapchat',
    TikTok = 'TikTok',
    Reddit = 'Reddit',
    Quora = 'Quora',
    Yelp = 'Yelp',
    Campaign = 'Campaign',
    Other = 'Other'
};
export enum CreateLeadCommandPriorityEnum {
    Low = 'Low',
    Medium = 'Medium',
    High = 'High',
    Critical = 'Critical'
};



