/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCallLogCommand { 
    /**
     * Entity Id, ContactId / ClientId
     */
    toId: string;
    /**
     * Contact number
     */
    toContact: string;
    /**
     * Twilio Call SID
     */
    callSid: string;
    /**
     * Entity type
     */
    entityType: CreateCallLogCommandEntityTypeEnum;
    /**
     * Call duration in seconds
     */
    duration: number;
    /**
     * Call started date
     */
    startDate: string;
    /**
     * Call ended dated
     */
    endDate: string;
    /**
     * Call Status
     */
    status: string;
    /**
     * Call direction
     */
    direction?: CreateCallLogCommandDirectionEnum;
    /**
     * Telephony provider
     */
    provider?: CreateCallLogCommandProviderEnum;
    /**
     * Recording URL
     */
    recordingUrl?: string;
    /**
     * Recording SID
     */
    recordingSid?: string;
    /**
     * Call disposition
     */
    disposition?: string;
    /**
     * Call note
     */
    note?: string;
    /**
     * Follow-up date
     */
    followUpDate?: string;
    /**
     * Follow-up action
     */
    followUpAction?: string;
}
export enum CreateCallLogCommandEntityTypeEnum {
    Contact = 'Contact',
    Client = 'Client'
};
export enum CreateCallLogCommandDirectionEnum {
    Inbound = 'inbound',
    Outbound = 'outbound'
};
export enum CreateCallLogCommandProviderEnum {
    Twilio = 'twilio',
    Ringover = 'ringover',
    Asterisk = 'asterisk'
};



