/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCurrencyCommand { 
    /**
     * ISO 4217 currency code
     */
    code: string;
    /**
     * Currency display name
     */
    name: string;
    /**
     * Currency symbol
     */
    symbol: string;
    /**
     * Currency exchange rate to default currency
     */
    rate: number;
    isDefault?: boolean;
}

