/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PremiumStructureDto } from './premium-structure-dto.interface';
import { ProductVariantDto } from './product-variant-dto.interface';
import { ProductFeeDto } from './product-fee-dto.interface';


export interface CreateProductCommand { 
    name: string;
    type: CreateProductCommandTypeEnum;
    description?: string;
    interestRate?: number;
    duration?: number;
    fees?: Array<ProductFeeDto>;
    eligibilityCriteria?: Array<string>;
    variants?: Array<ProductVariantDto>;
    insuranceType?: CreateProductCommandInsuranceTypeEnum;
    premiumStructure?: PremiumStructureDto;
    coverage?: string;
    deductible?: number;
    terms?: string;
    metadata?: object;
}
export enum CreateProductCommandTypeEnum {
    Loan = 'loan',
    Savings = 'savings',
    Insurance = 'insurance'
};
export enum CreateProductCommandInsuranceTypeEnum {
    Life = 'life',
    Health = 'health',
    Property = 'property'
};



