/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateAgencyAddressDto } from './create-agency-address-dto.interface';


export interface CreateAgencyCommand { 
    /**
     * Territory ID, the territory where the office will be linked
     */
    territoryId: string;
    /**
     * Agency name
     */
    name: string;
    address: CreateAgencyAddressDto;
}

