/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AudienceFilterDto } from './audience-filter-dto.interface';


export interface EstimateAudienceQuery { 
    /**
     * Filters to apply to the contact list to estimate the audience size
     */
    filters: Array<AudienceFilterDto>;
}

