/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterDto } from './filter-dto.interface';


export interface FilterAllClientsCommand { 
    status?: FilterDto;
    kycStatus?: FilterDto;
    accountType?: FilterDto;
    assignedToUserId?: FilterDto;
    territoryId?: FilterDto;
    createdAt?: FilterDto;
}

