/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterDto } from './filter-dto.interface';


export interface FilterAllLeadsCommand { 
    /**
     * Filter by fullName
     */
    fullName?: FilterDto;
    /**
     * Filter by email
     */
    email?: FilterDto;
    /**
     * Filter by mobileNumber
     */
    mobileNumber?: FilterDto;
    /**
     * Filter by status (eq or in)
     */
    status?: FilterDto;
    /**
     * Filter by source (eq or in)
     */
    source?: FilterDto;
    /**
     * Filter by priority (eq or in)
     */
    priority?: FilterDto;
    /**
     * Filter by territoryId
     */
    territoryId?: FilterDto;
    /**
     * Filter by agencyId
     */
    agencyId?: FilterDto;
    /**
     * Filter by assignedToTeamId
     */
    assignedToTeamId?: FilterDto;
    /**
     * Filter by assignedToUserId
     */
    assignedToUserId?: FilterDto;
    /**
     * Filter by tags (contain)
     */
    tags?: FilterDto;
    /**
     * Filter by createdAt (gte, lte)
     */
    createdAt?: FilterDto;
}

