/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FilterDto { 
    operator: FilterDtoOperatorEnum;
    /**
     * Value
     */
    value: string;
}
export enum FilterDtoOperatorEnum {
    Eq = 'eq',
    Lt = 'lt',
    Gte = 'gte',
    Lte = 'lte',
    Gt = 'gt',
    In = 'in',
    Nin = 'nin',
    Ne = 'ne',
    Contain = 'contain'
};



