/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreatedByInfoDto } from './created-by-info-dto.interface';
import { StatusHistoryDto } from './status-history-dto.interface';
import { AddressDto } from './address-dto.interface';


export interface FindContactByIdQueryResponse { 
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email?: string;
    /**
     * First name
     */
    firstName?: string;
    /**
     * Last name
     */
    lastName?: string;
    /**
     * Mobile number
     */
    mobileNumber?: string;
    /**
     * Phone number
     */
    phone?: string;
    /**
     * Date of birth
     */
    dateOfBirth?: string;
    /**
     * Date of creation
     */
    createdAt?: string;
    /**
     * Address
     */
    addresses?: Array<AddressDto>;
    /**
     * Job title
     */
    jobTitle: string;
    /**
     * Contact source
     */
    source: string;
    /**
     * Contact status
     */
    status: string;
    /**
     * Gender
     */
    gender?: string;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Company name
     */
    companyName?: string;
    /**
     * Assigned user ID
     */
    assignedToUserId?: string;
    /**
     * Assigned team ID
     */
    assignedToTeamId?: string;
    /**
     * Territory ID
     */
    territoryId?: string;
    /**
     * Agency ID
     */
    agencyId?: string;
    /**
     * Created by info
     */
    createdByInfo?: CreatedByInfoDto;
    /**
     * Status history
     */
    statusHistory: Array<StatusHistoryDto>;
}

