/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FindAllMeetingsQueryResponse { 
    /**
     * Meeting ID
     */
    id: string;
    /**
     * Related to entity ID
     */
    relatedToId: string;
    /**
     * Meeting title
     */
    title: string;
    /**
     * Meeting description
     */
    description: string;
    /**
     * Meeting location
     */
    location: string;
    /**
     * Meeting start time
     */
    startAt: object;
    /**
     * Meeting end time
     */
    endAt: object;
    /**
     * Created date
     */
    createdAt: string;
}

