/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FindAllTerritoriesQueryResponse { 
    id: string;
    name: string;
    /**
     * Date of creation
     */
    createdAt: string;
    /**
     * Latest updated At
     */
    updatedAt: string;
    /**
     * Person who created the entry
     */
    createdBy: string;
    /**
     * Name of the territory parent if so
     */
    parentName: string;
}

