/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldResponse } from './field-response.interface';


export interface FindFormByIdQueryResponse { 
    id: string;
    formClass: string;
    name: string;
    isActive: boolean;
    metadata?: object;
    fields: Array<FieldResponse>;
    createdAt: string;
    updatedAt: string;
}

