/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FindTelephonyConfigResponse { 
    id: string;
    provider: string;
    isActive: boolean;
    twilioConfig?: object;
    ringoverConfig?: object;
    asteriskConfig?: object;
    recordingEnabled: boolean;
    recordingConsent: string;
}

