/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RingoverConfigDto } from './ringover-config-dto.interface';
import { TwilioConfigDto } from './twilio-config-dto.interface';
import { AsteriskConfigDto } from './asterisk-config-dto.interface';


export interface FindTelephonyConfigResponse { 
    id: string;
    provider: string;
    isActive: boolean;
    /**
     * Twilio configuration details, if provider is Twilio
     */
    twilioConfig?: TwilioConfigDto;
    /**
     * RingOver configuration details, if provider is RingOver
     */
    ringoverConfig?: RingoverConfigDto;
    /**
     * Asterisk configuration details, if provider is Asterisk
     */
    asteriskConfig?: AsteriskConfigDto;
    recordingEnabled: boolean;
    recordingConsent: string;
}

