/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FromAgentLiteDto } from './from-agent-lite-dto.interface';


export interface FindAllCallLogsQueryResponse { 
    /**
     * Call log id
     */
    id: string;
    /**
     * Related entity id, e.g., ContactId / ClientId
     */
    relatedToId: string;
    /**
     * Twilio call SID
     */
    callSid: string;
    /**
     * Recipient\'s contact number
     */
    recipientContact: string;
    /**
     * Call duration in seconds
     */
    duration: number;
    /**
     * Call status
     */
    status: string;
    /**
     * Call note
     */
    note: string;
    /**
     * Call start date
     */
    startDate: string;
    /**
     * Call end date
     */
    endDate?: string;
    /**
     * Agent who placed the call
     */
    fromAgentLite?: FromAgentLiteDto;
    /**
     * Created date
     */
    createdAt: string;
    /**
     * Call direction (inbound/outbound)
     */
    direction?: string;
    /**
     * Telephony provider
     */
    provider?: string;
    /**
     * Call disposition
     */
    disposition?: string;
    /**
     * Follow-up date
     */
    followUpDate?: string;
    /**
     * Follow-up action
     */
    followUpAction?: string;
    /**
     * Recording URL
     */
    recordingUrl?: string;
}

