/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FindMeetingByIdQueryResponse { 
    id: string;
    title: string;
    description: string;
    location: string;
    startAt: object;
    endAt: object;
    ownerId: string;
    relatedToId: string;
    relatedToType: string;
    attendees: Array<string>;
    eventTypeId: string;
    status: string;
    outcome: string;
    outcomeNotes: string;
    followUpEventId: string;
    reminderMinutesBefore: number;
    meetingTimeZone: string;
    createdAt: string;
}

