/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreatedByInfoDto } from './created-by-info-dto.interface';
import { StatusHistoryDto } from './status-history-dto.interface';


export interface FindLeadByIdQueryResponse { 
    id: string;
    email: string;
    firstName: string;
    lastName: string;
    mobileNumber: string;
    phone?: string;
    dateOfBirth?: string;
    createdAt: string;
    source: string;
    status: string;
    gender?: string;
    tags: Array<string>;
    companyName?: string;
    jobTitle?: string;
    assignedToUserId?: string;
    assignedToTeamId?: string;
    territoryId?: string;
    agencyId?: string;
    createdByInfo?: CreatedByInfoDto;
    statusHistory: Array<StatusHistoryDto>;
    productInterest?: string;
    estimatedValue?: number;
    priority?: string;
    notes?: string;
    bantBudget?: string;
    bantAuthority?: string;
    bantNeed?: string;
    bantTimeline?: string;
    disqualificationReason?: string;
    score?: number;
    customFields?: object;
}

