/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FindByClassNameFieldDto { 
    id: string;
    name: string;
    type: string;
    options?: Array<string>;
    visible: boolean;
    /**
     * Whether the field is required or not
     */
    required: boolean;
    /**
     * Whether the field is a custom field or not
     */
    custom: boolean;
    /**
     * The position of the field in the form
     */
    position: number;
    /**
     * The label of the field
     */
    label: string;
    /**
     * The placeholder of the field
     */
    placeholder?: string;
    /**
     * The hint of the field
     */
    hint?: string;
}

