/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FindProductByIdQueryResponse { 
    id: string;
    name: string;
    type: string;
    status: string;
    environment: string;
    description?: string;
    interestRate?: number;
    duration?: number;
    fees?: Array<string>;
    eligibilityCriteria?: Array<string>;
    variants?: Array<string>;
    insuranceType?: string;
    premiumStructure?: object;
    coverage?: string;
    deductible?: number;
    terms?: string;
    metadata?: object;
    testRunCount: number;
    promotedAt?: string;
    promotedBy?: string;
    createdAt: string;
    updatedAt: string;
}

