/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FindAllTeamsQueryUserDto } from './find-all-teams-query-user-dto.interface';


export interface FindAllTeamsQueryResponse { 
    id: string;
    name: string;
    description: string;
    manager: FindAllTeamsQueryUserDto;
    members: Array<FindAllTeamsQueryUserDto>;
    /**
     * Date of creation
     */
    createdAt: string;
    /**
     * Created by user information
     */
    createdBy: FindAllTeamsQueryUserDto;
    /**
     * Date of last update
     */
    updatedAt: string;
}

