/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TerritoryLiteDto } from './territory-lite-dto.interface';
import { TerritoriesQueryUserDto } from './territories-query-user-dto.interface';


export interface FindAllTerritoriesQueryResponse { 
    id: string;
    /**
     * Name of the territory
     */
    name: string;
    /**
     * Date of creation
     */
    createdAt: string;
    /**
     * Latest updated At
     */
    updatedAt: string;
    /**
     * Person who created the entry
     */
    createdByInfo?: TerritoriesQueryUserDto;
    /**
     * Name of the territory parent if so
     */
    parentInfo?: TerritoryLiteDto;
    children?: Array<TerritoryLiteDto>;
}

