/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreatedByInfoDto } from './created-by-info-dto.interface';


export interface GetAllUserQuery { 
    userId: string;
    /**
     * User email 
     */
    email: string;
    firstName: string;
    lastName: string;
    createdAt: string;
    updatedAt: string;
    /**
     * Information of the owner of the record
     */
    createdByInfo: CreatedByInfoDto;
}

