/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LinkedInCommenter } from './linked-in-commenter.interface';


export interface ImportLinkedInPostCommandRequest { 
    postUrl: string;
    commenters: Array<LinkedInCommenter>;
}

