/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InviteUserCommand { 
    /**
     * User email
     */
    email: string;
    /**
     * FirstName
     */
    firstName: string;
    /**
     * LastName
     */
    lastName: string;
    /**
     * Job title
     */
    jobTitle: string;
    /**
     * Work number
     */
    workNumber: string;
    /**
     * Mobile number
     */
    mobileNumber: string;
    /**
     * The user will report to this person
     */
    reportTo: string;
    /**
     * The user role id
     */
    role: string;
    /**
     * List of teams the user is linked
     */
    teams: Array<string>;
}

