/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterBase } from './filter-base.interface';


export interface PaginateAllUsersCommand { 
    filters: FilterBase;
    sort?: object;
    /**
     * Page Index
     */
    pageIndex: number;
    pageSize: number;
}

