/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginateAllUsersTeamDto } from './paginate-all-users-team-dto.interface';


export interface PaginateAllUsersCommandDto { 
    id: string;
    email: string;
    isVerified: boolean;
    isActive: boolean;
    roles: Array<string>;
    permissions: Array<string>;
    teams: Array<PaginateAllUsersTeamDto>;
    createdAt: string;
    updatedAt: string;
}

