/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoutingStrategyDto { 
    method: RoutingStrategyDtoMethodEnum;
    params?: object;
}
export enum RoutingStrategyDtoMethodEnum {
    RoundRobin = 'round_robin',
    LeastLoaded = 'least_loaded',
    SkillBased = 'skill_based',
    TerritoryBased = 'territory_based',
    FirstAvailable = 'first_available',
    CustomScore = 'custom_score'
};



