/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SetMeetingOutcomeCommand { 
    /**
     * Outcome value
     */
    outcome: SetMeetingOutcomeCommandOutcomeEnum;
    /**
     * Outcome notes
     */
    outcomeNotes?: string;
}
export enum SetMeetingOutcomeCommandOutcomeEnum {
    Completed = 'completed',
    NoShow = 'no-show',
    Rescheduled = 'rescheduled',
    Cancelled = 'cancelled'
};



