/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginateAllTerritoriesCommand } from './paginate-all-territories-command.interface';


export interface TerritoriesControllerPaginateAllTerritoriesV1200Response { 
    /**
     * 
     */
    totalElements: number;
    pageIndex: number;
    pageSize: number;
    totalPages: number;
    data: Array<PaginateAllTerritoriesCommand>;
}

