/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TwilioAccessTokenResponse { 
    /**
     * Toke
     */
    token: string;
    /**
     * The connected Agent name
     */
    identity: string;
}

