/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoutingRuleDto } from './routing-rule-dto.interface';


export interface UpdateCaptureConfigCommandRequest { 
    name?: string;
    isActive?: boolean;
    allowedDomains?: Array<string>;
    fieldMapping?: object;
    routingRule?: RoutingRuleDto;
}

