/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateMessageTemplateCommandRequest { 
    name?: string;
    channel?: UpdateMessageTemplateCommandRequestChannelEnum;
    subject?: string;
    body?: string;
    category?: string;
    mergeFields?: Array<string>;
    isWhatsAppApproved?: boolean;
    whatsAppTemplateId?: string;
}
export enum UpdateMessageTemplateCommandRequestChannelEnum {
    Email = 'email',
    Sms = 'sms',
    Whatsapp = 'whatsapp'
};



