/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AudienceFilterDto } from './audience-filter-dto.interface';


export interface UpdateCampaignCommandRequest { 
    name?: string;
    channel?: UpdateCampaignCommandRequestChannelEnum;
    templateId?: string;
    subject?: string;
    body?: string;
    audienceFilters?: Array<AudienceFilterDto>;
    scheduledAt?: string;
}
export enum UpdateCampaignCommandRequestChannelEnum {
    Email = 'email',
    Sms = 'sms',
    Whatsapp = 'whatsapp'
};



