/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateDealCommandRequest { 
    title?: string;
    amount?: number;
    contactId?: string;
    contactName?: string;
    assignedTo?: string;
    assignedToName?: string;
    expectedCloseDate?: string;
    notes?: string;
    tags?: Array<string>;
}

