/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDto } from './address-dto.interface';


export interface UpdateContactCommandRequest { 
    /**
     * Contact firstName
     */
    firstName?: string;
    /**
     * Contact lastName
     */
    lastName?: string;
    /**
     * Contact Email
     */
    email?: string;
    /**
     * Contact mobileNumber
     */
    mobileNumber?: string;
    /**
     * Contact job title
     */
    jobTitle?: string;
    /**
     * Contact Address
     */
    address?: AddressDto;
}

