/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateEventTypeCommand { 
    /**
     * Event type name
     */
    name?: string;
    /**
     * Feather icon name
     */
    icon?: string;
    /**
     * Hex color
     */
    color?: string;
    /**
     * Default duration in minutes
     */
    defaultDurationMinutes?: number;
    /**
     * Required fields
     */
    requiredFields?: Array<string>;
    /**
     * Active status
     */
    isActive?: boolean;
}

