/**
 * Talisoft.Lotchen.API
 * The Lotchen API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RingOverConfigDto } from './ring-over-config-dto.interface';
import { TwilioConfigDto } from './twilio-config-dto.interface';
import { AsteriskConfigDto } from './asterisk-config-dto.interface';


export interface UpsertTelephonyConfigCommand { 
    /**
     * Telephony provider
     */
    provider: UpsertTelephonyConfigCommandProviderEnum;
    twilioConfig?: TwilioConfigDto;
    ringoverConfig?: RingOverConfigDto;
    asteriskConfig?: AsteriskConfigDto;
    recordingEnabled?: boolean;
    recordingConsent?: UpsertTelephonyConfigCommandRecordingConsentEnum;
}
export enum UpsertTelephonyConfigCommandProviderEnum {
    Twilio = 'twilio',
    Ringover = 'ringover',
    Asterisk = 'asterisk'
};
export enum UpsertTelephonyConfigCommandRecordingConsentEnum {
    AutoAnnounce = 'auto-announce',
    Manual = 'manual',
    Disabled = 'disabled'
};



