export * from './agencies.service';
import { AgenciesApiService } from './agencies.service';
export * from './auth.service';
import { AuthApiService } from './auth.service';
export * from './call-logs.service';
import { CallLogsApiService } from './call-logs.service';
export * from './caller.service';
import { CallerApiService } from './caller.service';
export * from './campaigns.service';
import { CampaignsApiService } from './campaigns.service';
export * from './contacts.service';
import { ContactsApiService } from './contacts.service';
export * from './currencies.service';
import { CurrenciesApiService } from './currencies.service';
export * from './deals.service';
import { DealsApiService } from './deals.service';
export * from './event-types.service';
import { EventTypesApiService } from './event-types.service';
export * from './lead-capture-configs.service';
import { LeadCaptureConfigsApiService } from './lead-capture-configs.service';
export * from './leads.service';
import { LeadsApiService } from './leads.service';
export * from './meetings.service';
import { MeetingsApiService } from './meetings.service';
export * from './message-templates.service';
import { MessageTemplatesApiService } from './message-templates.service';
export * from './notes.service';
import { NotesApiService } from './notes.service';
export * from './organizations.service';
import { OrganizationsApiService } from './organizations.service';
export * from './permissions.service';
import { PermissionsApiService } from './permissions.service';
export * from './profile.service';
import { ProfileApiService } from './profile.service';
export * from './roles.service';
import { RolesApiService } from './roles.service';
export * from './sales-pipelines.service';
import { SalesPipelinesApiService } from './sales-pipelines.service';
export * from './tasks.service';
import { TasksApiService } from './tasks.service';
export * from './teams.service';
import { TeamsApiService } from './teams.service';
export * from './telephony-config.service';
import { TelephonyConfigApiService } from './telephony-config.service';
export * from './territories.service';
import { TerritoriesApiService } from './territories.service';
export * from './users.service';
import { UsersApiService } from './users.service';
export * from './workflow-executions.service';
import { WorkflowExecutionsApiService } from './workflow-executions.service';
export * from './workflow-templates.service';
import { WorkflowTemplatesApiService } from './workflow-templates.service';
export const APIS = [AgenciesApiService, AuthApiService, CallLogsApiService, CallerApiService, CampaignsApiService, ContactsApiService, CurrenciesApiService, DealsApiService, EventTypesApiService, LeadCaptureConfigsApiService, LeadsApiService, MeetingsApiService, MessageTemplatesApiService, NotesApiService, OrganizationsApiService, PermissionsApiService, ProfileApiService, RolesApiService, SalesPipelinesApiService, TasksApiService, TeamsApiService, TelephonyConfigApiService, TerritoriesApiService, UsersApiService, WorkflowExecutionsApiService, WorkflowTemplatesApiService];
