export * from './agencies.service';
import { AgenciesApiService } from './agencies.service';
export * from './auth.service';
import { AuthApiService } from './auth.service';
export * from './call-logs.service';
import { CallLogsApiService } from './call-logs.service';
export * from './caller.service';
import { CallerApiService } from './caller.service';
export * from './contacts.service';
import { ContactsApiService } from './contacts.service';
export * from './event-types.service';
import { EventTypesApiService } from './event-types.service';
export * from './leads.service';
import { LeadsApiService } from './leads.service';
export * from './meetings.service';
import { MeetingsApiService } from './meetings.service';
export * from './notes.service';
import { NotesApiService } from './notes.service';
export * from './organizations.service';
import { OrganizationsApiService } from './organizations.service';
export * from './permissions.service';
import { PermissionsApiService } from './permissions.service';
export * from './profile.service';
import { ProfileApiService } from './profile.service';
export * from './roles.service';
import { RolesApiService } from './roles.service';
export * from './tasks.service';
import { TasksApiService } from './tasks.service';
export * from './teams.service';
import { TeamsApiService } from './teams.service';
export * from './territories.service';
import { TerritoriesApiService } from './territories.service';
export * from './users.service';
import { UsersApiService } from './users.service';
export * from './workflow-executions.service';
import { WorkflowExecutionsApiService } from './workflow-executions.service';
export * from './workflow-templates.service';
import { WorkflowTemplatesApiService } from './workflow-templates.service';
export const APIS = [AgenciesApiService, AuthApiService, CallLogsApiService, CallerApiService, ContactsApiService, EventTypesApiService, LeadsApiService, MeetingsApiService, NotesApiService, OrganizationsApiService, PermissionsApiService, ProfileApiService, RolesApiService, TasksApiService, TeamsApiService, TerritoriesApiService, UsersApiService, WorkflowExecutionsApiService, WorkflowTemplatesApiService];
